"""Initial migration

Revision ID: 47a4e3dd6e3a
Revises: 
Create Date: 2026-06-08 20:18:32.465976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a4e3dd6e3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('object_class', sa.String(), nullable=True),
    sa.Column('traffic_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_logs_id'), 'traffic_logs', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_logs_object_class'), 'traffic_logs', ['object_class'], unique=False)
    op.create_index(op.f('ix_traffic_logs_traffic_state'), 'traffic_logs', ['traffic_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_logs_traffic_state'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_object_class'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_id'), table_name='traffic_logs')
    op.drop_table('traffic_logs')
    # ### end Alembic commands ###
